export function premiereShiftSnapFixPlugin() {
  return {
    name: 'premiere-shift-snap-fix',
    enforce: 'pre',
    transform(code, id) {
      if (!id.includes('src/App.jsx')) return null
      let out = code

      const oldBlock = [
        '  const startBlockDrag = (e, block, mode) => {',
        '    e.stopPropagation();',
        '    e.preventDefault();',
        '    commitHistory();',
        '    setSelectedBlockId(block.id);',
        '    setPreviewCostumeId(block.costumeId);',
        '    const snapPoints = getSnapPoints(block.id);',
        '    dragRef.current = { mode, id: block.id, startX: e.clientX, s0: block.start, d0: block.dur };',
        '    const move = (ev) => {',
        '      const d = dragRef.current;',
        '      if (!d) return;',
        '      const dt = (ev.clientX - d.startX) / pps;',
        '      const snapOn = ev.shiftKey;',
        '      const threshold = 16 / pps; // SHIFT: 16px 자석 반경 · 재생헤드/다른 블록 시작·끝에 스냅',
        '      let guideT = null;',
        '',
        '      setBlocks((bs) =>',
        '        bs.map((b) => {',
        '          if (b.id !== d.id) return b;',
        '          if (d.mode === "move") {',
        '            let ns = Math.max(0, Math.min(duration - b.dur, d.s0 + dt));',
        '            if (snapOn) {',
        '              const snappedStart = snapTime(ns, snapPoints, threshold);',
        '              const snappedFromEnd = snapTime(ns + b.dur, snapPoints, threshold) - b.dur;',
        '              const useEnd = Math.abs(snappedFromEnd - ns) < Math.abs(snappedStart - ns);',
        '              const snapped = useEnd ? snappedFromEnd : snappedStart;',
        '              if (snapped !== ns) guideT = useEnd ? snapped + b.dur : snapped;',
        '              ns = Math.max(0, Math.min(duration - b.dur, snapped));',
        '            }',
        '            return { ...b, start: ns };',
        '          }',
        '          if (d.mode === "l") {',
        '            let ns = Math.max(0, Math.min(d.s0 + d.d0 - 0.2, d.s0 + dt));',
        '            if (snapOn) {',
        '              const snapped = snapTime(ns, snapPoints, threshold);',
        '              if (snapped !== ns) guideT = snapped;',
        '              ns = Math.max(0, Math.min(d.s0 + d.d0 - 0.2, snapped));',
        '            }',
        '            return { ...b, start: ns, dur: d.s0 + d.d0 - ns };',
        '          }',
        '          let nd = Math.max(0.2, Math.min(duration - d.s0, d.d0 + dt));',
        '          if (snapOn) {',
        '            const endT = d.s0 + nd;',
        '            const snappedEnd = snapTime(endT, snapPoints, threshold);',
        '            if (snappedEnd !== endT) guideT = snappedEnd;',
        '            nd = Math.max(0.2, Math.min(duration - d.s0, snappedEnd - d.s0));',
        '          }',
        '          return { ...b, dur: nd };',
        '        })',
        '      );',
        '      setSnapGuide(guideT);',
        '    };',
        '    const up = () => {',
        '      dragRef.current = null;',
        '      setSnapGuide(null);',
        '      window.removeEventListener("mousemove", move);',
        '      window.removeEventListener("mouseup", up);',
        '    };',
        '    window.addEventListener("mousemove", move);',
        '    window.addEventListener("mouseup", up);',
        '  };',
      ].join('\n')

      const newBlock = [
        '  const startBlockDrag = (e, block, mode) => {',
        '    e.stopPropagation();',
        '    e.preventDefault();',
        '    commitHistory();',
        '    setSelectedBlockId(block.id);',
        '    setPreviewCostumeId(block.costumeId);',
        '',
        '    // SHIFT를 누른 동안에만 Premiere처럼 자석 스냅을 활성화한다.',
        '    // 마우스 이벤트의 shiftKey만 믿지 않고 드래그 중 keydown/keyup도 추적해서',
        '    // SHIFT를 먼저 누르거나 드래그 도중 누르는 두 경우를 모두 처리한다.',
        '    let shiftHeld = !!e.shiftKey;',
        '    const shiftDown = (ke) => { if (ke.key === "Shift") shiftHeld = true; };',
        '    const shiftUp = (ke) => { if (ke.key === "Shift") { shiftHeld = false; setSnapGuide(null); } };',
        '    window.addEventListener("keydown", shiftDown);',
        '    window.addEventListener("keyup", shiftUp);',
        '',
        '    dragRef.current = { mode, id: block.id, startX: e.clientX, s0: block.start, d0: block.dur };',
        '    const move = (ev) => {',
        '      const d = dragRef.current;',
        '      if (!d) return;',
        '      const dt = (ev.clientX - d.startX) / pps;',
        '      const snapOn = shiftHeld || ev.shiftKey;',
        '      const threshold = 20 / pps; // SHIFT 전용 20px 자석 반경',
        '      let guideT = null;',
        '',
        '      setBlocks((bs) => {',
        '        // 매 mousemove마다 현재 블록 배열에서 기준점을 다시 만든다.',
        '        // 대상: 0초 + 빨간 재생헤드 + 다른 모든 블록의 시작/끝.',
        '        const snapPoints = [0, currentTime];',
        '        bs.forEach((other) => {',
        '          if (other.id === d.id) return;',
        '          snapPoints.push(other.start, other.start + other.dur);',
        '        });',
        '',
        '        return bs.map((b) => {',
        '          if (b.id !== d.id) return b;',
        '',
        '          if (d.mode === "move") {',
        '            const rawStart = Math.max(0, Math.min(duration - b.dur, d.s0 + dt));',
        '            let ns = rawStart;',
        '            if (snapOn) {',
        '              // 블록의 왼쪽(start)과 오른쪽(end) 중 목표점에 더 가까운 쪽을 붙인다.',
        '              let bestStart = rawStart;',
        '              let bestGuide = null;',
        '              let bestDist = threshold;',
        '              snapPoints.forEach((point) => {',
        '                const startDist = Math.abs(point - rawStart);',
        '                if (startDist <= bestDist) {',
        '                  bestDist = startDist;',
        '                  bestStart = point;',
        '                  bestGuide = point;',
        '                }',
        '                const endDist = Math.abs(point - (rawStart + b.dur));',
        '                if (endDist < bestDist) {',
        '                  bestDist = endDist;',
        '                  bestStart = point - b.dur;',
        '                  bestGuide = point;',
        '                }',
        '              });',
        '              ns = Math.max(0, Math.min(duration - b.dur, bestStart));',
        '              guideT = bestGuide;',
        '            }',
        '            return { ...b, start: ns };',
        '          }',
        '',
        '          if (d.mode === "l") {',
        '            const rawStart = Math.max(0, Math.min(d.s0 + d.d0 - 0.2, d.s0 + dt));',
        '            let ns = rawStart;',
        '            if (snapOn) {',
        '              const snapped = snapTime(rawStart, snapPoints, threshold);',
        '              if (Math.abs(snapped - rawStart) <= threshold && snapped !== rawStart) guideT = snapped;',
        '              ns = Math.max(0, Math.min(d.s0 + d.d0 - 0.2, snapped));',
        '            }',
        '            return { ...b, start: ns, dur: d.s0 + d.d0 - ns };',
        '          }',
        '',
        '          const rawDur = Math.max(0.2, Math.min(duration - d.s0, d.d0 + dt));',
        '          let nd = rawDur;',
        '          if (snapOn) {',
        '            const rawEnd = d.s0 + rawDur;',
        '            const snappedEnd = snapTime(rawEnd, snapPoints, threshold);',
        '            if (Math.abs(snappedEnd - rawEnd) <= threshold && snappedEnd !== rawEnd) guideT = snappedEnd;',
        '            nd = Math.max(0.2, Math.min(duration - d.s0, snappedEnd - d.s0));',
        '          }',
        '          return { ...b, dur: nd };',
        '        });',
        '      });',
        '',
        '      // SHIFT가 아닐 때는 스냅 가이드를 절대 표시하지 않는다.',
        '      setSnapGuide(snapOn ? guideT : null);',
        '    };',
        '',
        '    const up = () => {',
        '      dragRef.current = null;',
        '      setSnapGuide(null);',
        '      window.removeEventListener("mousemove", move);',
        '      window.removeEventListener("mouseup", up);',
        '      window.removeEventListener("keydown", shiftDown);',
        '      window.removeEventListener("keyup", shiftUp);',
        '    };',
        '    window.addEventListener("mousemove", move);',
        '    window.addEventListener("mouseup", up);',
        '  };',
      ].join('\n')

      if (!out.includes(oldBlock)) {
        throw new Error('premiere shift snap fix: transformed startBlockDrag anchor not found')
      }
      out = out.replace(oldBlock, newBlock)

      // Runtime/build assertion: both block-edge targets and the playhead must remain in the snap list.
      if (!out.includes('const snapPoints = [0, currentTime]') || !out.includes('snapPoints.push(other.start, other.start + other.dur)')) {
        throw new Error('premiere shift snap fix: snap targets missing')
      }

      return { code: out, map: null }
    },
  }
}
