const replaceBetween = (code, start, end, replacement, label) => {
  const from = code.indexOf(start)
  if (from < 0) throw new Error(`sync live worklet fix: ${label} start anchor not found`)
  const to = code.indexOf(end, from)
  if (to < 0) throw new Error(`sync live worklet fix: ${label} end anchor not found`)
  return code.slice(0, from) + replacement + code.slice(to)
}

export function syncLiveAudioWorkletFixPlugin() {
  return {
    name: 'sync-live-audio-worklet-fix',
    enforce: 'pre',
    transform(code, id) {
      if (!id.includes('src/SyncLiveAppV3.jsx')) return null
      if (!code.includes('const refreshMicDevices = async')) return null

      const micBlock = [
        "  const refreshMicDevices = async (preferredId = '') => {",
        "    try {",
        "      const devices = (await navigator.mediaDevices.enumerateDevices()).filter((d) => d.kind === 'audioinput')",
        "      setMicDevices(devices)",
        "      if (preferredId) setMicDeviceId(preferredId)",
        "      return devices",
        "    } catch { return [] }",
        "  }",
        "",
        "  const stopMic = async (reason = 'MIC STOP') => {",
        "    const m = micRef.current; micRef.current = null",
        "    if (m) {",
        "      if (m.silenceTimer) window.clearTimeout(m.silenceTimer)",
        "      try { m.worklet?.port && (m.worklet.port.onmessage = null); m.worklet?.disconnect(); m.source?.disconnect(); m.pullGain?.disconnect() } catch {}",
        "      m.stream?.getTracks().forEach((t) => { t.onended = null; t.onmute = null; t.onunmute = null; t.stop() })",
        "      await m.ctx?.close().catch(() => {})",
        "    }",
        "    setMicActive(false); setMicStatus('MIC OFF'); setMicEngineStatus('IDLE'); setInputDb(-90); holdFootage('HOLD · MIC OFF'); disarm(reason)",
        "  }",
        "",
        "  const startMic = async () => {",
        "    if (micRef.current) return stopMic()",
        "    if (!navigator.mediaDevices?.getUserMedia) return notify('이 브라우저에서는 마이크 입력을 사용할 수 없습니다.')",
        "    setMicStatus('MIC STARTING…'); setMicEngineStatus('REQUESTING RAW PCM'); setInputDb(-90)",
        "    try {",
        "      const requestedAudio = micDeviceId ? { deviceId: { exact: micDeviceId } } : true",
        "      let stream",
        "      try { stream = await navigator.mediaDevices.getUserMedia({ video: false, audio: requestedAudio }) }",
        "      catch (firstError) {",
        "        if (!micDeviceId) throw firstError",
        "        log(`MIC DEVICE FALLBACK · ${firstError?.name || 'Error'}`)",
        "        stream = await navigator.mediaDevices.getUserMedia({ video: false, audio: true })",
        "      }",
        "      const track = stream.getAudioTracks()[0]",
        "      if (!track) throw new Error('사용 가능한 오디오 입력 트랙이 없습니다.')",
        "      const Ctx = window.AudioContext || window.webkitAudioContext",
        "      if (!Ctx) throw new Error('Web Audio API를 사용할 수 없습니다.')",
        "      const ctx = new Ctx({ latencyHint: 'interactive' })",
        "      await ctx.resume()",
        "      if (!ctx.audioWorklet || typeof AudioWorkletNode === 'undefined') throw new Error('AudioWorklet을 지원하지 않는 브라우저입니다. Chrome/Edge 최신 버전을 사용하세요.')",
        "",
        "      const workletSource = [",
        "        'class SyncLiveMicCapture extends AudioWorkletProcessor {',",
        "        '  constructor() { super(); this.buf = new Float32Array(1024); this.pos = 0; this.sum = 0; this.peak = 0; }',",
        "        '  process(inputs) {',",
        "        '    const input = inputs[0]; const ch = input && input[0]; if (!ch || !ch.length) return true;',",
        "        '    for (let i = 0; i < ch.length; i += 1) {',",
        "        '      const v = ch[i]; this.buf[this.pos++] = v; this.sum += v * v; const a = Math.abs(v); if (a > this.peak) this.peak = a;',",
        "        '      if (this.pos >= this.buf.length) { const out = this.buf; this.port.postMessage({ samples: out, peak: this.peak, rms: Math.sqrt(this.sum / out.length) }, [out.buffer]); this.buf = new Float32Array(1024); this.pos = 0; this.sum = 0; this.peak = 0; }',",
        "        '    }',",
        "        '    return true;',",
        "        '  }',",
        "        '}',",
        "        \"registerProcessor('sync-live-mic-capture', SyncLiveMicCapture)\",",
        "      ].join('\\n')",
        "      const moduleUrl = URL.createObjectURL(new Blob([workletSource], { type: 'application/javascript' }))",
        "      try { await ctx.audioWorklet.addModule(moduleUrl) } finally { URL.revokeObjectURL(moduleUrl) }",
        "",
        "      const source = ctx.createMediaStreamSource(stream)",
        "      const worklet = new AudioWorkletNode(ctx, 'sync-live-mic-capture', { numberOfInputs: 1, numberOfOutputs: 1, outputChannelCount: [1] })",
        "      const pullGain = ctx.createGain(); pullGain.gain.value = 0.0000001",
        "      source.connect(worklet); worklet.connect(pullGain); pullGain.connect(ctx.destination)",
        "",
        "      const settings = track.getSettings?.() || {}",
        "      const deviceName = track.label || (settings.deviceId ? '선택된 입력 장치' : '기본 입력 장치')",
        "      await refreshMicDevices(settings.deviceId || '')",
        "      let blocks = 0, zeroBlocks = 0, sawSignal = false, lastFeatureAt = 0",
        "",
        "      worklet.port.onmessage = (ev) => {",
        "        if (micRef.current?.track !== track) return",
        "        const samples = ev.data?.samples instanceof Float32Array ? ev.data.samples : new Float32Array(ev.data?.samples || [])",
        "        const peak = Number(ev.data?.peak || 0)",
        "        const rms = Number(ev.data?.rms || 0)",
        "        const db = clamp(20 * Math.log10(Math.max(rms, 0.00001)), -90, 0)",
        "        setInputDb(db); blocks += 1",
        "        if (peak <= 0.000001) zeroBlocks += 1; else zeroBlocks = 0",
        "        if (peak > 0.00008 || db > -85) sawSignal = true",
        "        if (blocks % 5 === 0) setMicEngineStatus(`AUDIOWORKLET · ${blocks} blocks · peak ${peak.toExponential(1)}`)",
        "        if (zeroBlocks === 40) { setMicStatus(`${deviceName} · RAW PCM ZERO · macOS 입력 확인`); log(`MIC RAW PCM ZERO · device=${deviceName} · muted=${track.muted ? 1 : 0} · ready=${track.readyState}`) }",
        "        const now = performance.now()",
        "        if (matcherRef.current && peak > 0.000001 && samples.length >= FFT_SIZE && now - lastFeatureAt >= FRAME_SEC * 1000) { lastFeatureAt = now; onFeature(extractFeature(samples.subarray(0, FFT_SIZE), ctx.sampleRate)) }",
        "      }",
        "",
        "      const silenceTimer = window.setTimeout(() => {",
        "        if (micRef.current?.track !== track || sawSignal) return",
        "        setMicStatus(`${deviceName} · RAW PCM ZERO · macOS 입력 확인`)",
        "        log(`MIC ZERO AFTER WORKLET · device=${deviceName} · muted=${track.muted ? 1 : 0} · enabled=${track.enabled ? 1 : 0}`)",
        "      }, 1800)",
        "",
        "      track.onended = () => { setMicStatus('MIC TRACK ENDED'); setMicEngineStatus('TRACK ENDED'); setMicActive(false); setInputDb(-90); micRef.current = null; disarm('MIC TRACK ENDED') }",
        "      track.onmute = () => setMicStatus(`${deviceName} · MUTED BY OS/BROWSER`)",
        "      track.onunmute = () => setMicStatus(`${deviceName} ACTIVE`)",
        "      micRef.current = { stream, track, ctx, source, worklet, pullGain, silenceTimer }",
        "      matcherRef.current?.reset(); rt.current.lastLockedPosition = null",
        "      setMicActive(true); setMicDeviceName(deviceName); setMicEngineStatus(`AUDIOWORKLET · ${ctx.sampleRate} Hz`); setMicStatus(`${deviceName} ACTIVE`)",
        "      setFootageStatus(footageUrlRef.current ? 'SEARCHING · LOCK 대기' : 'WAITING FOR FOOTAGE')",
        "      log(`MIC WORKLET ACTIVE · ${deviceName} · ${ctx.sampleRate}Hz · muted=${track.muted ? 1 : 0} · ready=${track.readyState}`)",
        "      if (!reference) log('MIC TEST MODE · REFERENCE 없이 입력 레벨만 측정 중')",
        "    } catch (e) {",
        "      const name = e?.name || 'Error'; const message = e?.message || '마이크 시작 실패'",
        "      setMicActive(false); setMicEngineStatus(name); setMicStatus(`MIC ERROR · ${name}`); setInputDb(-90)",
        "      notify(message); log(`MIC ERROR · ${name} · ${message}`)",
        "    }",
        "  }",
        "",
      ].join('\n')

      const next = replaceBetween(code, '  const refreshMicDevices = async', '  const toggleArm = async', micBlock, 'mic implementation')
      return { code: next, map: null }
    },
  }
}
